/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by tests/q1000k/pon_phy_probe_steps.py. Do not edit. */
static const struct qprobe_step xpon_dig_reset_hold[] = {
	{ EN7581_XPON_PMA_SW_RST_SET, 6, 6, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 5, 5, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 4, 4, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 3, 3, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 2, 2, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 1, 1, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 0, 0, 0x00, 0 },
};
static const struct qprobe_step xpon_dig_reset_release[] = {
	{ EN7581_XPON_PMA_SW_RST_SET, 5, 5, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 1, 1, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 2, 2, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 3, 3, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 6, 6, 0x01, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 4, 4, 0x01, 0 },
};
static const struct qprobe_step xpon_rx_l2r[] = {
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 0, 0, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 8, 8, 0x01, 0 },
	{ 0, 0, 0, 0, 100 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x01, 0 },
};
static const struct qprobe_step xpon_rx_l2d[] = {
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x01, 0 },
	{ 0, 0, 0, 0, 200 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 8, 8, 0x01, 0 },
};
static const struct qprobe_step xpon_tdc_off[] = {
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_pr_idac, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_3, 8, 8, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_sdm_pcw_chg, 8, 8, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_sdm_pcw_chg, 0, 0, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_sdm_pcw_chg, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_1, 0, 0, 0x00, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_PW_0, 0, 0, 0x00, 0 },
};
static const struct qprobe_step xpon_tdc_on[] = {
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_6, 9, 8, 0x00, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_0, 1, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_sdm_pcw_chg, 8, 8, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_pr_idac, 24, 24, 0x00, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_PW_5, 16, 16, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_3, 8, 8, 0x00, 0 },
	{ 0, 0, 0, 0, 100 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_5, 16, 16, 0x00, 0 },
	{ 0, 0, 0, 0, 100 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_FLT_1, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_TDC_PW_0, 0, 0, 0x01, 0 },
	{ 0, 0, 0, 0, 500 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x00, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_cdr_lpf_lck2data, 16, 16, 0x01, 0 },
};
static const struct qprobe_step txpll_on[] = {
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_ckout_en, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_ckout_en, 16, 16, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_LCPLL_PWCTL_SETTING_0, 24, 24, 0x01, 0 },
	{ 0, 0, 0, 0, 6 },
	{ EN7581_XPON_ANA_RG_PXP_JCPLL_FREQ_MEAS_EN, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_ckout_en, 8, 8, 0x01, 0 },
	{ EN7581_XPON_PMA_rg_force_da_pxp_txpll_ckout_en, 0, 0, 0x01, 0 },
	{ EN7581_XPON_ANA_RG_PXP_TXPLL_TCL_KBAND_VREF, 16, 16, 0x01, 0 },
	{ EN7581_XPON_ANA_RG_PXP_TXPLL_TCL_KBAND_VREF, 8, 8, 0x00, 0 },
	{ EN7581_XPON_ANA_RG_PXP_TXPLL_PHY_CK1_EN, 8, 8, 0x01, 0 },
	{ EN7581_XPON_ANA_RG_PXP_TXPLL_PHY_CK1_EN, 0, 0, 0x01, 0 },
	{ EN7581_XPON_ANA_RG_PXP_JCPLL_FREQ_MEAS_EN, 0, 0, 0x00, 0 },
	{ EN7581_XPON_ANA_RG_PXP_JCPLL_FREQ_MEAS_EN, 24, 24, 0x00, 0 },
	{ EN7581_XPON_ANA_RG_PXP_JCPLL_FREQ_MEAS_EN, 16, 16, 0x00, 0 },
	{ 0, 0, 0, 0, 500 },
};
static const struct qprobe_step xpon_fll_reset[] = {
	{ EN7581_XPON_PMA_SS_RX_FLL_3, 0, 0, 0x00, 0 },
	{ 0, 0, 0, 0, 500 },
	{ EN7581_XPON_PMA_SS_RX_FLL_3, 0, 0, 0x01, 0 },
	{ EN7581_XPON_PMA_SS_RX_FLL_3, 8, 8, 0x00, 0 },
	{ 0, 0, 0, 0, 500 },
	{ EN7581_XPON_PMA_SS_RX_FLL_3, 8, 8, 0x01, 0 },
};
static const struct qprobe_step xpon_rx_rxrdy[] = {
	{ EN7581_XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1, 24, 24, 0x01, 0 },
	{ EN7581_XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1, 24, 24, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 0, 0, 0x00, 0 },
	{ EN7581_XPON_PMA_SW_RST_SET, 0, 0, 0x01, 0 },
};
