#!/bin/sh /etc/rc.common

USE_PROCD=1
START=21
STOP=19

start_service() {
	procd_open_instance
	procd_set_param command /bin/true
	procd_close_instance
	/usr/share/bridge-hw-offload/apply-rules.sh
}

service_triggers() {
	procd_add_reload_trigger firewall network
}

reload_service() {
	/usr/share/bridge-hw-offload/apply-rules.sh
}

stop_service() (
	mkdir -p /var/lock
	exec 9>/var/lock/bridge-hw-offload.lock
	flock -x 9 || return 1
	rm -f /var/run/bridge-hw-offload/bridge.nft
	nft destroy table bridge fw4
)
