#!/bin/sh

[ "$ACTION" = ifup ] || exit 0
[ "$INTERFACE" = lan ] || exit 0

(
	exec 9>/var/lock/bridge-hw-offload.lock
	flock -n 9 || exit 0
	sleep 10
	/usr/share/bridge-hw-offload/apply-rules.sh
) &

exit 0
