#!/usr/bin/env python3
"""Extract only the named public register sequences; never execute vendor code."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
PHY = ROOT / 'package/kernel/airoha-pon/src/xpon-en757x/xpon_phy_10g'
FUNCTIONS = ('XPON_DIG_reset_hold', 'XPON_DIG_reset_release', 'XPON_RX_L2R',
             'XPON_RX_L2D', 'XPON_TDC_off', 'XPON_TDC_on', 'TXPLL_on',
             'XPON_FLL_Reset', 'XPON_RX_rxrdy')


def generate():
    source = (PHY / 'src/en7581_pma.c').read_text()
    source = re.sub(r'/\*.*?\*/|//[^\n]*', '', source, flags=re.S)
    out = ['/* SPDX-License-Identifier: GPL-2.0-only */',
           '/* Generated by tests/q1000k/pon_phy_probe_steps.py. Do not edit. */']
    for name in FUNCTIONS:
        start = source.index('void ' + name + '(void)')
        start = source.index('{', start) + 1
        depth, end = 1, start
        while depth:
            depth += (source[end] == '{') - (source[end] == '}')
            end += 1
        body = source[start:end - 1]
        # The selected routines have only disabled debug/efuse blocks. Nested
        # blocks in the disabled efuse section must stay excluded too.
        lines, disabled = [], 0
        for line in body.splitlines():
            if line.lstrip().startswith('#if'):
                if not disabled and not re.match(r'\s*#if\s+(0\b|LAB_PRINT_PON\b)', line):
                    raise ValueError('Unknown conditional in ' + name)
                disabled += 1
            elif line.lstrip().startswith('#endif'):
                disabled -= 1
            elif not disabled:
                lines.append(line)
        if disabled:
            raise ValueError('Unbalanced conditional in ' + name)
        out.append('static const struct qprobe_step ' + name.lower() + '[] = {')
        for statement in '\n'.join(lines).split(';'):
            statement = statement.strip()
            if not statement or statement == 'UINT32 read_data':
                continue
            write = re.fullmatch(r'IO_SPHYA_REG_BITS\(\s*(EN7581_\w+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\)', statement)
            delay = re.fullmatch(r'udelay\((\d+)\)', statement)
            if write:
                out.append('\t{ ' + ', '.join(write.groups()) + ', 0 },')
            elif delay:
                out.append('\t{ 0, 0, 0, 0, ' + delay[1] + ' },')
            else:
                raise ValueError('Unexpected statement in ' + name + ': ' + statement)
        out.append('};')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    print(generate(), end='')
